const pool = require("./db/connect");

pool.connect();

const sales = [
  {
    user_id: 40,
    store_name: "Adelaide Craft Fair",
    contact: "0412345678",
    description: "Join us for the Adelaide Craft Fair on June 12th!",
    location: "Adelaide Showground",
    items: "Handmade jewelry, pottery, paintings, and more",
    latitude: "-34.952965",
    longitude: "138.594151",
  },

  {
    user_id: 40,
    store_name: "Melbourne Vintage Clothing Sale",
    contact: "0412345678",
    description: "Vintage clothing sale on June 19th",
    location: "50 Lonsdale St, Melbourne",
    items: "Vintage dresses, hats, shoes, and accessories",
    latitude: "-37.810073",
    longitude: "144.969432",
  },

  {
    user_id: 40,
    store_name: "Brisbane Farmer's Market",
    contact: "0412345678",
    description: "Fresh produce and local crafts every Sunday!",
    location: "97 Boundary St, West End",
    items: "Fresh fruit, vegetables, baked goods, and handmade crafts",
    latitude: "-27.480045",
    longitude: "153.012038",
  },

  {
    user_id: 40,
    store_name: "Sydney Record Fair",
    contact: "0412345678",
    description: "Thousands of vinyl records for sale on July 3rd",
    location: "Marrickville Town Hall",
    items: "Rock, jazz, blues, soul, and more",
    latitude: "-33.910001",
    longitude: "151.155496",
  },

  {
    user_id: 40,
    store_name: "Adelaide Farmers Market",
    contact: "0412345678",
    description: "Fresh produce every Saturday morning!",
    location: "Wayville Showgrounds",
    items: "Fruit, vegetables, dairy products, and meat",
    latitude: "-34.955579",
    longitude: "138.594127",
  },

  {
    user_id: 40,
    store_name: "Melbourne Pop-up Shop",
    contact: "0412345678",
    description: "Limited time only! Pop-up shop on July 10th",
    location: "100 Swanston St, Melbourne",
    items: "Clothing, shoes, accessories, and homeware",
    latitude: "-37.817492",
    longitude: "144.965485",
  },

  {
    user_id: 40,
    store_name: "Brisbane Art Exhibition",
    contact: "0412345678",
    description: "Contemporary art exhibition on August 14th",
    location: "QUT Art Museum",
    items: "Paintings, sculptures, and installations",
    latitude: "-27.476956",
    longitude: "153.015719",
  },
  {
    user_id: 40,
    store_name: "Sydney Flea Market",
    contact: "0412345678",
    description: "Second-hand bargains every Sunday",
    location: "Sydney Markets Plaza",
    items: "Clothing, shoes, books, and household items",
    latitude: "-33.902687",
    longitude: "151.185343",
  },

  {
    user_id: 40,
    store_name: "Adelaide Street Art Tour",
    contact: "0412345678",
    description: "Discover the best street art in Adelaide!",
    location: "Starting point: Rundle Mall",
    items: "Guided tour of the city's street art",
    latitude: "-34.922363",
    longitude: "138.606827",
  },

  {
    user_id: 40,
    store_name: "Melbourne Design Market",
    contact: "0412345678",
    description: "Unique and innovative design products on August 21st",
    location: "The Meat Market",
    items: "Homeware, jewelry, furniture, and more",
    latitude: "-37.803401",
    longitude: "144.957102",
  },

  {
    user_id: 40,
    store_name: "Brisbane Organic Market",
    contact: "0412345678",
    description: "Organic and sustainable products every Saturday",
    location: "Eagle Farm Markets",
    items: "Organic fruit, vegetables, meat, and dairy products",
    latitude: "-27.437230",
    longitude: "153.072170",
  },

  {
    user_id: 40,
    store_name: "Sydney Artisan Market",
    contact: "0412345678",
    description: "Handcrafted products every Sunday",
    location: "The Rocks",
    items: "Jewelry, pottery, candles, and more",
    latitude: "-33.859958",
    longitude: "151.208768",
  },

  {
    user_id: 40,
    store_name: "Adelaide Wine Tasting",
    contact: "0412345678",
    description: "Sample the best South Australian wines on September 4th",
    location: "National Wine Centre",
    items: "Wine tastings and sales",
    latitude: "-34.918082",
    longitude: "138.607373",
  },

  {
    user_id: 40,
    store_name: "Melbourne Craft Market",
    contact: "0412345678",
    description: "Handmade crafts every Saturday",
    location: "Federation Square",
    items: "Jewelry, clothing, candles, and more",
    latitude: "-37.817641",
    longitude: "144.968747",
  },
  {
    user_id: 40,
    store_name: "Sydney Night Market",
    contact: "0412345678",
    description: "Food, drink, and entertainment every Friday night",
    location: "Carriageworks",
    items: "Street food, cocktails, and live music",
    latitude: "-33.895358",
    longitude: "151.195006",
  },

  {
    user_id: 40,
    store_name: "Adelaide Farmers Market",
    contact: "0412345678",
    description: "Fresh and local produce every Sunday morning",
    location: "Adelaide Showground",
    items: "Fruits, vegetables, dairy products, and more",
    latitude: "-34.955215",
    longitude: "138.596164",
  },

  {
    user_id: 40,
    store_name: "Melbourne Fashion Market",
    contact: "0412345678",
    description: "Fashion and accessories on September 11th",
    location: "Coburg Town Hall",
    items: "Clothing, bags, shoes, and jewelry",
    latitude: "-37.744461",
    longitude: "144.961716",
  },

  {
    user_id: 40,
    store_name: "Brisbane Street Food Festival",
    contact: "0412345678",
    description: "International food and drink on August 28th",
    location: "South Bank Parklands",
    items: "Street food, beer, and wine",
    latitude: "-27.481018",
    longitude: "153.023447",
  },

  {
    user_id: 40,
    store_name: "Sydney Vintage Market",
    contact: "0412345678",
    description: "Vintage clothing and accessories every Saturday",
    location: "Marrickville Town Hall",
    items: "Vintage clothing, accessories, and homeware",
    latitude: "-33.904681",
    longitude: "151.156358",
  },

  {
    user_id: 40,
    store_name: "Adelaide Book Fair",
    contact: "0412345678",
    description: "Second-hand books and magazines on August 14th",
    location: "Adelaide Showground",
    items: "Books, magazines, and comics",
    latitude: "-34.955215",
    longitude: "138.596164",
  },

  {
    user_id: 40,
    store_name: "Melbourne Craft Beer Festival",
    contact: "0412345678",
    description: "Craft beer and food on September 25th",
    location: "Catani Gardens",
    items: "Craft beer, food, and live music",
    latitude: "-37.858798",
    longitude: "144.969688",
  },

  {
    user_id: 40,
    store_name: "Brisbane Flower Market",
    contact: "0412345678",
    description: "Fresh flowers and plants every Sunday morning",
    location: "Rocklea Markets",
    items: "Flowers, plants, and gardening supplies",
    latitude: "-27.546223",
    longitude: "153.017073",
  },
  {
    user_id: 40,
    store_name: "Sydney Christmas Market",
    contact: "0412345678",
    description: "Handmade gifts and decorations on December 10th",
    location: "The Cutaway, Barangaroo Reserve",
    items: "Handmade gifts, decorations, and Christmas treats",
    latitude: "-33.862620",
    longitude: "151.201170",
  },

  {
    user_id: 40,
    store_name: "Adelaide Art and Craft Market",
    contact: "0412345678",
    description: "Handmade art and crafts on September 18th",
    location: "Plant 4 Bowden",
    items: "Handmade art, crafts, and jewelry",
    latitude: "-34.903737",
    longitude: "138.572214",
  },

  {
    user_id: 40,
    store_name: "Melbourne Night Noodle Markets",
    contact: "0412345678",
    description: "Asian food and entertainment on November 12th",
    location: "Birrarung Marr",
    items: "Asian street food, drinks, and live music",
    latitude: "-37.820546",
    longitude: "144.971989",
  },

  {
    user_id: 40,
    store_name: "Brisbane Handmade Market",
    contact: "0412345678",
    description: "Handmade gifts and crafts on October 2nd",
    location: "Riverside Centre",
    items: "Handmade gifts, crafts, and homeware",
    latitude: "-27.466344",
    longitude: "153.029008",
  },

  {
    user_id: 40,
    store_name: "Sydney Fish Market",
    contact: "0412345678",
    description: "Fresh seafood and fish every day",
    location: "Pyrmont",
    items: "Fish, seafood, and sushi",
    latitude: "-33.857763",
    longitude: "151.194975",
  },

  {
    user_id: 40,
    store_name: "Adelaide Vegan Market",
    contact: "0412345678",
    description: "Vegan food, drinks, and products on October 30th",
    location: "Plant 4 Bowden",
    items: "Vegan food, drinks, and products",
    latitude: "-34.903737",
    longitude: "138.572214",
  },

  {
    user_id: 40,
    store_name: "Melbourne Street Art Tour",
    contact: "0412345678",
    description: "Guided street art tour every Saturday",
    location: "Hosier Lane",
    items: "Guided street art tour",
    latitude: "-37.815865",
    longitude: "144.967068",
  },
  {
    user_id: 40,
    store_name: "Brisbane Night Market",
    contact: "0412345678",
    description: "Food, drinks, and live music every Friday night",
    location: "Eat Street Northshore",
    items: "Street food, drinks, and live music",
    latitude: "-27.400893",
    longitude: "153.056282",
  },

  {
    user_id: 40,
    store_name: "Sydney Vintage Market",
    contact: "0412345678",
    description: "Vintage clothing and accessories on November 19th",
    location: "Marrickville Town Hall",
    items: "Vintage clothing and accessories",
    latitude: "-33.910752",
    longitude: "151.159296",
  },

  {
    user_id: 40,
    store_name: "Adelaide Farmers' Market",
    contact: "0412345678",
    description: "Fresh produce and artisan goods every Sunday",
    location: "Adelaide Showground",
    items: "Fresh produce, artisan goods, and food trucks",
    latitude: "-34.957430",
    longitude: "138.588282",
  },

  {
    user_id: 40,
    store_name: "Melbourne Book Market",
    contact: "0412345678",
    description: "Second-hand books and comics on October 16th",
    location: "Queen Victoria Market",
    items: "Second-hand books, comics, and zines",
    latitude: "-37.807206",
    longitude: "144.958125",
  },

  {
    user_id: 40,
    store_name: "Brisbane Art and Design Market",
    contact: "0412345678",
    description: "Art and design market on November 6th",
    location: "King George Square",
    items: "Art, design, and handmade goods",
    latitude: "-27.468299",
    longitude: "153.024353",
  },

  {
    user_id: 40,
    store_name: "Sydney Night Noodle Markets",
    contact: "0412345678",
    description: "Asian food and entertainment on October 29th",
    location: "Hyde Park",
    items: "Asian street food, drinks, and live music",
    latitude: "-33.873552",
    longitude: "151.213454",
  },

  {
    user_id: 40,
    store_name: "Adelaide Beachfront Market",
    contact: "0412345678",
    description: "Beachfront market every Saturday",
    location: "Semaphore Beach",
    items: "Local produce, handmade goods, and clothing",
    latitude: "-34.841802",
    longitude: "138.485376",
  },

  {
    user_id: 40,
    store_name: "Melbourne Flower Market",
    contact: "0412345678",
    description: "Wholesale flower market every Tuesday",
    location: "Footscray",
    items: "Fresh flowers and plants",
    latitude: "-37.796288",
    longitude: "144.900068",
  },
  {
    user_id: 40,
    store_name: "Brisbane Riverside Markets",
    contact: "0412345678",
    description: "Craft and artisan market every Sunday",
    location: "Eagle Street Pier",
    items: "Crafts, artisan goods, and food stalls",
    latitude: "-27.468794",
    longitude: "153.030684",
  },

  {
    user_id: 40,
    store_name: "Sydney Fish Market",
    contact: "0412345678",
    description: "Fresh seafood every day",
    location: "Bank Street, Pyrmont",
    items: "Fresh seafood and sushi",
    latitude: "-33.866939",
    longitude: "151.195032",
  },
];

let sql =
  "INSERT INTO listing(user_id, store_name, contact, description, location, items, latitude, longitude) VALUES($1,$2,$3,$4,$5,$6,$7,$8);";

sales.map((sale) => {
  pool.query(sql, [
    sale.user_id,
    sale.store_name,
    sale.contact,
    sale.description,
    sale.location,
    sale.items,
    sale.latitude,
    sale.longitude,
  ]);
});
